### ISSUE TITLE
Implement Events

### ISSUE THREAD

**Issue by joserick** [joserick/v-money-spinner#1]
In base to vuejs-tips/v-money/issues/63, 

Implement the events:
- When the number changes
- When the number fell to negative
- When the number fell to positive
- When the minimum or maximum allowed value is exceeded

**Comment by l0nely-island** [comment]
Any progress on this?

**Comment by joserick** [comment]
Hi @chris-snader 

An apology, I had forgotten this topic but between today and tomorrow, this should be ready.

**Comment by joleth08** [comment]
Hi, I have same issue. Anyway this plugin is perfect, especially if this have a events like onchange.

**Comment by l0nely-island** [comment]
I was able to use @change.native instead of @change, but it worked the same as @input which didn't quite work for me. The work around I'm using right now is @blur.native. It's not exactly what I want, but it works as I'm trying to save to the database when the money field changes, but I don't want to update the database until the field loses focus.

**Comment by joleth08** [comment]
> I was able to use @change.native instead of @change, but it worked the same as @input which didn't quite work for me. The work around I'm using right now is @blur.native. It's not exactly what I want, but it works as I'm trying to save to the database when the money field changes, but I don't want to update the database until the field loses focus.

I tried @blur, but doesn't work for me.

**Comment by l0nely-island** [comment]
try @blur.native. That should work. Or at least it did for me. The onchange would still be nice to have though since I would love to only send the database change if the money field changed and the field then lost focus.

**Comment by joleth08** [comment]
@change.native worked for me. Thanks, I'm just a beginner here.

**Comment by joserick** [comment]
It's ready @chris-snader @joleth08 

Here are the events with some parameters: [Events](https://github.com/joserick/v-money-spinner#events)

If you have any problem or recommendation, do not hesitate to tell me
