### ISSUE TITLE
cursor on the left

### ISSUE THREAD

**Issue by luisrossi** [joserick/v-money-spinner#10]
When I click on the input, it starts with the cursor on the left, being necessary to remove what was typed before. Is it possible that he always starts on the right?

**Comment by joserick** [comment]
Hi @luisrossi 

Currently it's not possible... but since I've subtly abandoned this project, in this next month I'll proceed to recreate all the project structure for Vue 3 and in this I'll take into account this problem to solve it in the process.

**Comment by jonathanpmartins** [comment]
hey @joserick,

`v-money3` tackle something similar in this issue: https://github.com/jonathanpmartins/v-money3/issues/20

**Comment by joserick** [comment]
Hi @jonathanpmartins 

Excellent work!, one less problem, then, I will focus on the "Spinner" and support for Bootstrap, Tailwindcss and personalized stype for Vue 3

I'll try to have it asap @luisrossi

**Comment by luisrossi** [comment]
@joserick @jonathanpmartins 
Thank you very much

**Comment by joserick** [comment]
Hi @luisrossi 
Ready the implementation of Money3 in VMoneySpinner (v1.2.0), you should no longer have the problem the cursor on the left.

**Comment by luisrossi** [comment]
Hi @joserick,
Unfortunately you used the version for VUE2, but thanks for the update, I will use it for future systems
