### ISSUE TITLE
Types not available

### ISSUE THREAD

**Issue by albertcito** [joserick/v-money-spinner#26]
This is the code when I install this library on my local:

![Screenshot 2023-03-15 at 12 42 01 PM](https://user-images.githubusercontent.com/1768483/225379868-794ec005-e7c3-4497-8343-4ec4f6ca4d4e.png)

There is not types. How can I add it?

**Comment by joserick** [comment]
Excellent point, this weekend I implement it.

**Comment by joserick** [comment]
@albertcito Implemented 4e793d5 | [v1.3.1](https://github.com/joserick/v-money-spinner/releases/tag/v1.3.1)
