### ISSUE TITLE
Error with big Integer | More than 18 digits

### ISSUE THREAD

**Issue by joserick** [joserick/v-money-spinner#8]
Error when has more than 18 digits: 

![Error](https://user-images.githubusercontent.com/15143699/107837772-2e8dbf80-6d68-11eb-8bbe-143c78f70903.gif)

Based in #vuejs-tips/v-money/issues/103

**Comment by joserick** [comment]
![test](https://user-images.githubusercontent.com/15143699/132255589-f88dc11b-4a4a-4a5d-9a69-3cd583158d1c.gif)

Ready, the addition and subtraction works big integer.

Thanks @jonathanpmartins for creating the BigNumber class.

**Comment by jonathanpmartins** [comment]
@joserick you are welcome!

`BigNumber` if very small and simple. It has only what is needed for `v-money3` to work with arbitrary precision.

Feel free to open a issue or a pull request to improve the class if needed.
